# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=30000']
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

- repo: https://github.com/rtts/djhtml
  rev: '3.0.7'
  hooks:
    - id: djhtml
      entry: djhtml --tabwidth 2
      files: ./django_mongodb_cli/templates/project_template/project_name/templates/default_urlconf.html
